# Generated by Django 5.0.6 on 2024-07-05 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0002_remove_user_product_description_and_more'),
    ]

    operations = [

    ]
